### ISSUE TITLE
🚀 Feature Request: Using CoPilot kit on it's own website

### ISSUE THREAD

**Issue by ZEviod** [CopilotKit/CopilotKit#746]
### 🎤 Tell us your idea

How about we add copilot kit assistant (bottom right like talk/chat assistant) that help users to navigate and resolve thier doubts effectively.

Instead of asking questions directly from the devs , copilot can assist well helping them resolving thier issue, like using the product on it's own site.

**Comment by ZEviod** [comment]
If this issue seems right to do, then i would like to work on it! Thank you!

**Comment by vikasyadav097** [comment]
Presenting a Copilot Kit Assistant that improves user experience by offering contextual, real-time assistance within your platform. This AI-powered assistant, which is positioned at the bottom-right of the screen, assists users in navigating and efficiently answering their questions without requiring them to get in touch with developers. Depending on the page or feature being used, it provides detailed instructions, troubleshooting advice, and immediate responses to frequently asked problems. In addition to being seamlessly integrated, the assistant can help new users navigate complicated courses or onboarding procedures. It consistently enhances user happiness by refining its recommendations based on user interactions. This lessens reliance on support staff, expedites the process of resolving issues, and guarantees that customers may fully utilize the platform on their own.

**Comment by SahibAjitSingh** [comment]
Adding a "Copilot Kit" assistant (a bottom-right chat/talk assistant) could significantly improve the user experience, especially for developers or users looking for quick resolutions. Here's how it can be beneficial and how you can implement it:

Benefits of a Copilot Kit Assistant:
1. **Real-Time Guidance**: The assistant can provide instant help, reducing the dependency on human support, especially for common issues.
2. **In-Product Support**: Instead of users leaving the interface or searching FAQs, they can interact with the assistant directly on the product page.
3. **Contextual Assistance**: Based on the page the user is on, the assistant can offer context-specific help.
4. **Automation of Repetitive Queries**: The assistant can handle common questions like "How to navigate the dashboard?" or "How to set up an account?" by providing guided tutorials or step-by-step instructions.
5. **Integration with Documentation**: The assistant can offer snippets from the documentation or link to relevant sections, saving time for users.
6. **Voice or Chat Options**: Giving users the option to talk or chat with the assistant adds flexibility, especially for those who prefer voice interactions.
7. **Learning from User Interactions**: Over time, the assistant can learn and suggest better responses, tailoring solutions based on past interactions.

### Features to Include:
- **Code Suggestions**: If this is for developers, it can suggest code snippets, similar to GitHub Copilot, but tailored to the platform's specific APIs or services.
- **FAQ and Docs Integration**: Link frequently asked questions and documentation into the assistant for easy retrieval.
- **User Behavior Monitoring**: It can track user activity and suggest help if the user appears stuck on a particular section or functionality.
- **Live Chat Escalation**: In case the assistant can't resolve the issue, provide a way to escalate it to a human operator or support agent.

### Implementation Plan:
1. **Choose a Chatbot Framework**: Start with frameworks like **Microsoft Bot Framework**, **Dialogflow** (Google), or **Rasa** for creating conversational agents.
2. **Train the Model**: If using AI-based systems, feed the assistant with FAQs, common user issues, and API documentation so it can provide intelligent suggestions.
3. **UI Integration**: Add the assistant as a small, fixed widget on the bottom-right corner of the application. You can use **React**, **Vue**, or plain JavaScript for the front-end integration.
4. **Feedback Loop**: Implement a feedback mechanism to collect data on whether the suggestions were helpful. This will allow continuous improvement.
5. **Testing**: Run A/B tests with users to see how effective the assistant is in resolving issues before fully deploying it.

Would you like a more detailed guide on a specific technology for building such an assistant?

**Comment by roman-rr** [comment]
## Solved: Embeddable CopilotKit Widget for Third-Party Sites (Intercom-style)

We built an embeddable chat widget powered by CopilotKit that any website can add with a simple `<script>` tag — no React required on the host page. Here's how.

### Architecture: iframe + loader.js

CopilotKit is a React SDK, so we wrap the entire chat UI in a **standalone Vite app** (`frontend-embed`) served inside an **iframe**. A tiny vanilla JS `loader.js` (~3KB) handles the bubble, iframe lifecycle, and open/close — identical to how Intercom, Crisp, Drift etc. work.

### Customer Integration (2 lines)

```html
<script>
  window.PixelwerkChat = {
    apiKey: "TENANT_ACCESS_KEY",
    server: "https://your-embed-server.com",
    mode: "popup"  // or "sidebar"
  };
</script>
<script src="https://your-embed-server.com/loader.js" defer></script>
```

### How It Works

1. **`loader.js`** (vanilla JS) injects:
   - A floating chat bubble button (bottom-right, customizable)
   - An `<iframe>` pointing to `{server}/embed?key={apiKey}&mode={mode}&title=...`
   - For sidebar mode: a full-height slide-in panel with backdrop overlay
   - `postMessage` communication between host page and iframe (close events, etc.)

2. **`frontend-embed`** (Vite + React app inside the iframe):
   - Full CopilotKit setup: `<CopilotKit>` → `<CopilotChat>` with AG-UI protocol streaming
   - Reads config (`apiKey`, `mode`, `title`, `agentId`) from URL query params
   - All API calls are **same-origin** (iframe loads from the embed server, which proxies `/copilotkit` and `/api` to the backend) — **zero CORS issues**
   - Supports tool call renders, RAG sources, suggestions, feedback thumbs up/down

3. **Two interface modes:**
   - `popup` — floating window near the bubble (default), bubble toggles between chat/close icons
   - `sidebar` — full-height slide-in panel from right edge, bubble hides when panel is open, backdrop overlay to dismiss

### Why iframe Instead of Shadow DOM?

We initially considered bundling CopilotKit into a single IIFE with Shadow DOM isolation, but:
- CopilotKit internally uses **Lit web components** and global CSS — Shadow DOM breaks these
- Portals and modals escape Shadow DOM boundaries
- iframe gives **perfect style isolation** with zero conflicts against host page CSS
- Same-origin iframe means no CORS complexity (the iframe and API are on the same domain)
- The host page's CSS can never break the widget, and vice versa

### Key CSS Fixes for CopilotKit in an iframe

CopilotKit's chat layout needs a few overrides when running in a constrained iframe:

```css
/* Convert to flex-column so footer sits below scroll area (not overlapping) */
.copilotKitChat {
  display: flex !important;
  flex-direction: column !important;
}
.copilotKitChat > div:first-child {
  flex: 1 1 0% !important;
  min-height: 0 !important;
  height: auto !important;
}
[data-chat-footer] {
  position: relative !important;
  flex-shrink: 0 !important;
}

/* Hide dev inspector */
cpk-web-inspector { display: none !important; }

/* Fix excessive user message padding (cpk:pt-10 = 40px) */
.copilotKitUserMessage { padding-top: 0 !important; }
```

### Vite Config (dev + prod proxy)

```ts
// vite.config.ts — proxy API calls so iframe stays same-origin
export default defineConfig({
  server: {
    proxy: {
      '^/copilotkit($|/)': { target: 'http://localhost:8000' },
      '^/api/': { target: 'http://localhost:8000' },
    },
  },
  preview: {
    proxy: { /* same as above */ },
  },
});
```

The regex `^/copilotkit($|/)` avoids accidentally proxying `/copilotkit-v2.css` (a static asset).

### Result

Works exactly like Intercom — customers paste a snippet, get a chat bubble, full streaming AI chat with tool calls, RAG sources, and feedback. No React knowledge required on the customer side.

Hope this helps anyone looking to embed CopilotKit on external/non-React sites!
